version: '2.1'
x-common: &common
  image: ${DOCKER_IMAGE_TAG}
  environment: &commont-env
    JWT_VALIDATE: 'False'
  mem_limit: 2G
  restart: always

services:
  prompt-chain:
    <<: *common
    container_name: beauty-app
    ports:
      - 3002:3000
    environment:
      <<: *commont-env
